### PR TITLE
docs: improve README.md

### PR DESCRIPTION
**Pull request by sryabkov**
- add required/optional for configuration parameters
- add info specifying to use slack channel/group names instead of IDs

I tried using slack channels IDs instead of names first. It would have saved time if the documentation had been more specific that names should be used instead of IDs.

### CODE REVIEW

**Comment by mrmartineau** [comment]
@sryabkov would also be good to add links and info about how to get the Slack & GitHub access tokens

**Comment by mrmartineau** [comment]
FWIW, the Slack Token needs to come from https://my.slack.com/services/new/bot and the GitHub token can be taken from https://github.com/settings/tokens

**Comment by diogoosorio** [comment]
@sryabkov although we're running this code internally at Talkdesk (multiple instances of it in a matter of fact), the project was internally pretty much abandoned / neglected since @rogeriopvl left the company.

My team was allowed to take over the project - I'm going to merge this PR for you, I hope you don't mind me doing so. 🙏 

Thanks for the contribution and sorry for the very (very) late feedback. 😅

**Comment by sryabkov** [comment]
👍

**Pull request merged**
